//
//  Countries.swift
//  CovidSafe
//
//  Copyright © 2020 All rights reserved.
//
import FlagKit

struct CountriesData {
    
    static let countryArray = ["Australia"]

    static let  countries =
        [
            // Country(name: "country_region_name_af".localizedString(), isoCode:"AF",phoneCode:"93", flag:Flag(countryCode: "AF")),
            Country(name: "country_region_name_al".localizedString(), isoCode:"AL",phoneCode:"355", flag:Flag(countryCode: "AL")),
            Country(name: "country_region_name_dz".localizedString(), isoCode:"DZ",phoneCode:"213", flag:Flag(countryCode: "DZ")),
            // Country(name: "country_region_name_ad".localizedString(), isoCode:"AD",phoneCode:"376", flag:Flag(countryCode: "AD")),
            Country(name: "country_region_name_ao".localizedString(), isoCode:"AO",phoneCode:"244", flag:Flag(countryCode: "AO")),
            Country(name: "country_region_name_ai".localizedString(), isoCode:"AI",phoneCode:"1", flag:Flag(countryCode: "AI")),
            Country(name: "country_region_name_ag".localizedString(), isoCode:"AG",phoneCode:"1", flag:Flag(countryCode: "AG")),
            Country(name: "country_region_name_ar".localizedString(), isoCode:"AR",phoneCode:"54", flag:Flag(countryCode: "AR")),
            Country(name: "country_region_name_am".localizedString(), isoCode:"AM",phoneCode:"374", flag:Flag(countryCode: "AM")),
            Country(name: "country_region_name_aw".localizedString(), isoCode:"AW",phoneCode:"297", flag:Flag(countryCode: "AW")),
            // Country(name: "country_region_name_au".localizedString(), isoCode:"AU",phoneCode:"61", flag:Flag(countryCode: "AU")),
            Country(name: "country_region_name_at".localizedString(), isoCode:"AT",phoneCode:"43", flag:Flag(countryCode: "AT")),
            Country(name: "country_region_name_az".localizedString(), isoCode:"AZ",phoneCode:"994", flag:Flag(countryCode: "AZ")),
            Country(name: "country_region_name_bs".localizedString(), isoCode:"BS",phoneCode:"1", flag:Flag(countryCode: "BS")),
            Country(name: "country_region_name_bh".localizedString(), isoCode:"BH",phoneCode:"973", flag:Flag(countryCode: "BH")),
            Country(name: "country_region_name_bd".localizedString(), isoCode:"BD",phoneCode:"880", flag:Flag(countryCode: "BD")),
            Country(name: "country_region_name_bb".localizedString(), isoCode:"BB",phoneCode:"1", flag:Flag(countryCode: "BB")),
            Country(name: "country_region_name_by".localizedString(), isoCode:"BY",phoneCode:"375", flag:Flag(countryCode: "BY")),
            Country(name: "country_region_name_be".localizedString(), isoCode:"BE",phoneCode:"32", flag:Flag(countryCode: "BE")),
            Country(name: "country_region_name_bz".localizedString(), isoCode:"BZ",phoneCode:"501", flag:Flag(countryCode: "BZ")),
            Country(name: "country_region_name_bj".localizedString(), isoCode:"BJ",phoneCode:"229", flag:Flag(countryCode: "BJ")),
            Country(name: "country_region_name_bm".localizedString(), isoCode:"BM",phoneCode:"1", flag:Flag(countryCode: "BM")),
            // Country(name: "country_region_name_bt".localizedString(), isoCode:"BT",phoneCode:"975", flag:Flag(countryCode: "BT")),
            Country(name: "country_region_name_bo".localizedString(), isoCode:"BO",phoneCode:"591", flag:Flag(countryCode: "BO")),
            Country(name: "country_region_name_ba".localizedString(), isoCode:"BA",phoneCode:"387", flag:Flag(countryCode: "BA")),
            Country(name: "country_region_name_bw".localizedString(), isoCode:"BW",phoneCode:"267", flag:Flag(countryCode: "BW")),
            Country(name: "country_region_name_br".localizedString(), isoCode:"BR",phoneCode:"55", flag:Flag(countryCode: "BR")),
            // Country(name: "country_region_name_bn".localizedString(), isoCode:"BN",phoneCode:"673", flag:Flag(countryCode: "BN")),
            Country(name: "country_region_name_bg".localizedString(), isoCode:"BG",phoneCode:"359", flag:Flag(countryCode: "BG")),
            Country(name: "country_region_name_bf".localizedString(), isoCode:"BF",phoneCode:"226", flag:Flag(countryCode: "BF")),
            // Country(name: "country_region_name_bi".localizedString(), isoCode:"BI",phoneCode:"257", flag:Flag(countryCode: "BI")),
            Country(name: "country_region_name_kh".localizedString(), isoCode:"KH",phoneCode:"855", flag:Flag(countryCode: "KH")),
            Country(name: "country_region_name_cm".localizedString(), isoCode:"CM",phoneCode:"237", flag:Flag(countryCode: "CM")),
            Country(name: "country_region_name_ca".localizedString(), isoCode:"CA",phoneCode:"1", flag:Flag(countryCode: "CA")),
            Country(name: "country_region_name_cv".localizedString(), isoCode:"CV",phoneCode:"238", flag:Flag(countryCode: "CV")),
            Country(name: "country_region_name_ky".localizedString(), isoCode:"KY",phoneCode:"1", flag:Flag(countryCode: "KY")),
            // Country(name: "country_region_name_cf".localizedString(), isoCode:"CF",phoneCode:"236", flag:Flag(countryCode: "CF")),
            // Country(name: "country_region_name_td".localizedString(), isoCode:"TD",phoneCode:"235", flag:Flag(countryCode: "TD")),
            Country(name: "country_region_name_cl".localizedString(), isoCode:"CL",phoneCode:"56", flag:Flag(countryCode: "CL")),
            Country(name: "country_region_name_cn".localizedString(), isoCode:"CN",phoneCode:"86", flag:Flag(countryCode: "CN")),
            Country(name: "country_region_name_co".localizedString(), isoCode:"CO",phoneCode:"57", flag:Flag(countryCode: "CO")),
            // Country(name: "country_region_name_km".localizedString(), isoCode:"KM",phoneCode:"269", flag:Flag(countryCode: "KM")),
            // Country(name: "country_region_name_ck".localizedString(), isoCode:"CK",phoneCode:"682", flag:Flag(countryCode: "CK")),
            Country(name: "country_region_name_cr".localizedString(), isoCode:"CR",phoneCode:"506", flag:Flag(countryCode: "CR")),
            Country(name: "country_region_name_hr".localizedString(), isoCode:"HR",phoneCode:"385", flag:Flag(countryCode: "HR")),
            Country(name: "country_region_name_cu".localizedString(), isoCode:"CU",phoneCode:"53", flag:Flag(countryCode: "CU")),
            Country(name: "country_region_name_cw".localizedString(), isoCode:"CW",phoneCode:"599", flag:Flag(countryCode: "CW")),
            Country(name: "country_region_name_cy".localizedString(), isoCode:"CY",phoneCode:"357", flag:Flag(countryCode: "CY")),
            Country(name: "country_region_name_cz".localizedString(), isoCode:"CZ",phoneCode:"420", flag:Flag(countryCode: "CZ")),
            // Country(name: "country_region_name_cd".localizedString(), isoCode:"CD",phoneCode:"243", flag:Flag(countryCode: "CD")),
            Country(name: "country_region_name_dk".localizedString(), isoCode:"DK",phoneCode:"45", flag:Flag(countryCode: "DK")),
            // Country(name: "country_region_name_dj".localizedString(), isoCode:"DJ",phoneCode:"253", flag:Flag(countryCode: "DJ")),
            Country(name: "country_region_name_dm".localizedString(), isoCode:"DM",phoneCode:"1", flag:Flag(countryCode: "DM")),
            Country(name: "country_region_name_do".localizedString(), isoCode:"DO",phoneCode:"1", flag:Flag(countryCode: "DO")),
            // Country(name: "country_region_name_tl".localizedString(), isoCode:"TL",phoneCode:"670", flag:Flag(countryCode: "TL")),
            Country(name: "country_region_name_ec".localizedString(), isoCode:"EC",phoneCode:"593", flag:Flag(countryCode: "EC")),
            // Country(name: "country_region_name_eg".localizedString(), isoCode:"EG",phoneCode:"20", flag:Flag(countryCode: "EG")),
            Country(name: "country_region_name_sv".localizedString(), isoCode:"SV",phoneCode:"503", flag:Flag(countryCode: "SV")),
            // Country(name: "country_region_name_gq".localizedString(), isoCode:"GQ",phoneCode:"240", flag:Flag(countryCode: "GQ")),
            Country(name: "country_region_name_ee".localizedString(), isoCode:"EE",phoneCode:"372", flag:Flag(countryCode: "EE")),
            // Country(name: "country_region_name_et".localizedString(), isoCode:"ET",phoneCode:"251", flag:Flag(countryCode: "ET")),
            // Country(name: "country_region_name_fo".localizedString(), isoCode:"FO",phoneCode:"298", flag:Flag(countryCode: "FO")),
            Country(name: "country_region_name_fj".localizedString(), isoCode:"FJ",phoneCode:"679", flag:Flag(countryCode: "FJ")),
            Country(name: "country_region_name_fi".localizedString(), isoCode:"FI",phoneCode:"358", flag:Flag(countryCode: "FI")),
            Country(name: "country_region_name_fr".localizedString(), isoCode:"FR",phoneCode:"33", flag:Flag(countryCode: "FR")),
            // Country(name: "country_region_name_gf".localizedString(), isoCode:"GF",phoneCode:"995", flag:Flag(countryCode: "GF")),
            Country(name: "country_region_name_ga".localizedString(), isoCode:"GA",phoneCode:"241", flag:Flag(countryCode: "GA")),
            // Country(name: "country_region_name_gm".localizedString(), isoCode:"GM",phoneCode:"220", flag:Flag(countryCode: "GM")),
            Country(name: "country_region_name_ge".localizedString(), isoCode:"GE",phoneCode:"995", flag:Flag(countryCode: "GE")),
            Country(name: "country_region_name_de".localizedString(), isoCode:"DE",phoneCode:"49", flag:Flag(countryCode: "DE")),
            Country(name: "country_region_name_gh".localizedString(), isoCode:"GH",phoneCode:"233", flag:Flag(countryCode: "GH")),
            // Country(name: "country_region_name_gi".localizedString(), isoCode:"GI",phoneCode:"350", flag:Flag(countryCode: "GI")),
            Country(name: "country_region_name_gr".localizedString(), isoCode:"GR",phoneCode:"30", flag:Flag(countryCode: "GR")),
            // Country(name: "country_region_name_gl".localizedString(), isoCode:"GL",phoneCode:"299", flag:Flag(countryCode: "GL")),
            Country(name: "country_region_name_gd".localizedString(), isoCode:"GD",phoneCode:"1", flag:Flag(countryCode: "GD")),
            // Country(name: "country_region_name_gp".localizedString(), isoCode:"GP",phoneCode:"224", flag:Flag(countryCode: "GP")),
            Country(name: "country_region_name_gu".localizedString(), isoCode:"GU",phoneCode:"1", flag:Flag(countryCode: "GU")),
            Country(name: "country_region_name_gt".localizedString(), isoCode:"GT",phoneCode:"502", flag:Flag(countryCode: "GT")),
            // Country(name: "country_region_name_gn".localizedString(), isoCode:"GN",phoneCode:"224", flag:Flag(countryCode: "GN")),
            Country(name: "country_region_name_gw".localizedString(), isoCode:"GW",phoneCode:"245", flag:Flag(countryCode: "GW")),
            // Country(name: "country_region_name_gy".localizedString(), isoCode:"GY",phoneCode:"592", flag:Flag(countryCode: "GY")),
            Country(name: "country_region_name_ht".localizedString(), isoCode:"HT",phoneCode:"509", flag:Flag(countryCode: "HT")),
            Country(name: "country_region_name_hn".localizedString(), isoCode:"HN",phoneCode:"504", flag:Flag(countryCode: "HN")),
            Country(name: "country_region_name_hk".localizedString(), isoCode:"HK",phoneCode:"852", flag:Flag(countryCode: "HK")),
            Country(name: "country_region_name_hu".localizedString(), isoCode:"HU",phoneCode:"36", flag:Flag(countryCode: "HU")),
            Country(name: "country_region_name_is".localizedString(), isoCode:"IS",phoneCode:"354", flag:Flag(countryCode: "IS")),
            Country(name: "country_region_name_in".localizedString(), isoCode:"IN",phoneCode:"91", flag:Flag(countryCode: "IN")),
            Country(name: "country_region_name_id".localizedString(), isoCode:"ID",phoneCode:"62", flag:Flag(countryCode: "ID")),
            Country(name: "country_region_name_iq".localizedString(), isoCode:"IQ",phoneCode:"964", flag:Flag(countryCode: "IQ")),
            Country(name: "country_region_name_ie".localizedString(), isoCode:"IE",phoneCode:"353", flag:Flag(countryCode: "IE")),
            Country(name: "country_region_name_il".localizedString(), isoCode:"IL",phoneCode:"972", flag:Flag(countryCode: "IL")),
            Country(name: "country_region_name_ir".localizedString(), isoCode:"IR",phoneCode:"98", flag:Flag(countryCode: "IR")),
            // Country(name: "country_region_name_it".localizedString(), isoCode:"IT",phoneCode:"39", flag:Flag(countryCode: "IT")),
            Country(name: "country_region_name_ci".localizedString(), isoCode:"CI",phoneCode:"225", flag:Flag(countryCode: "CI")),
            Country(name: "country_region_name_jm".localizedString(), isoCode:"JM",phoneCode:"1", flag:Flag(countryCode: "JM")),
            Country(name: "country_region_name_jp".localizedString(), isoCode:"JP",phoneCode:"81", flag:Flag(countryCode: "JP")),
            Country(name: "country_region_name_jo".localizedString(), isoCode:"JO",phoneCode:"962", flag:Flag(countryCode: "JO")),
            Country(name: "country_region_name_kz".localizedString(), isoCode:"KZ",phoneCode:"7", flag:Flag(countryCode: "KZ")),
            Country(name: "country_region_name_ke".localizedString(), isoCode:"KE",phoneCode:"254", flag:Flag(countryCode: "KE")),
            // Country(name: "country_region_name_ki".localizedString(), isoCode:"KI",phoneCode:"686", flag:Flag(countryCode: "KI")),
            Country(name: "country_region_name_kw".localizedString(), isoCode:"KW",phoneCode:"965", flag:Flag(countryCode: "KW")),
            Country(name: "country_region_name_kg".localizedString(), isoCode:"KG",phoneCode:"996", flag:Flag(countryCode: "KG")),
            Country(name: "country_region_name_la".localizedString(), isoCode:"LA",phoneCode:"856", flag:Flag(countryCode: "LA")),
            Country(name: "country_region_name_lv".localizedString(), isoCode:"LV",phoneCode:"371", flag:Flag(countryCode: "LV")),
            Country(name: "country_region_name_lb".localizedString(), isoCode:"LB",phoneCode:"961", flag:Flag(countryCode: "LB")),
            // Country(name: "country_region_name_ls".localizedString(), isoCode:"LS",phoneCode:"266", flag:Flag(countryCode: "LS")),
            // Country(name: "country_region_name_lr".localizedString(), isoCode:"LR",phoneCode:"231", flag:Flag(countryCode: "LR")),
            // Country(name: "country_region_name_ly".localizedString(), isoCode:"LY",phoneCode:"218", flag:Flag(countryCode: "LY")),
            Country(name: "country_region_name_li".localizedString(), isoCode:"LI",phoneCode:"423", flag:Flag(countryCode: "LI")),
            Country(name: "country_region_name_lt".localizedString(), isoCode:"LT",phoneCode:"370", flag:Flag(countryCode: "LT")),
            Country(name: "country_region_name_lu".localizedString(), isoCode:"LU",phoneCode:"352", flag:Flag(countryCode: "LU")),
            Country(name: "country_region_name_mo".localizedString(), isoCode:"MO",phoneCode:"853", flag:Flag(countryCode: "MO")),
            Country(name: "country_region_name_mk".localizedString(), isoCode:"MK",phoneCode:"389", flag:Flag(countryCode: "MK")),
            // Country(name: "country_region_name_mg".localizedString(), isoCode:"MG",phoneCode:"261", flag:Flag(countryCode: "MG")),
            // Country(name: "country_region_name_mw".localizedString(), isoCode:"MW",phoneCode:"265", flag:Flag(countryCode: "MW")),
            Country(name: "country_region_name_my".localizedString(), isoCode:"MY",phoneCode:"60", flag:Flag(countryCode: "MY")),
            // Country(name: "country_region_name_mv".localizedString(), isoCode:"MV",phoneCode:"960", flag:Flag(countryCode: "MV")),
            Country(name: "country_region_name_ml".localizedString(), isoCode:"ML",phoneCode:"223", flag:Flag(countryCode: "ML")),
            Country(name: "country_region_name_mt".localizedString(), isoCode:"MT",phoneCode:"356", flag:Flag(countryCode: "MT")),
            Country(name: "country_region_name_mq".localizedString(), isoCode:"MQ",phoneCode:"1", flag:Flag(countryCode: "MQ")),
            // Country(name: "country_region_name_mr".localizedString(), isoCode:"MR",phoneCode:"222", flag:Flag(countryCode: "MR")),
            Country(name: "country_region_name_mu".localizedString(), isoCode:"MU",phoneCode:"230", flag:Flag(countryCode: "MU")),
            Country(name: "country_region_name_mx".localizedString(), isoCode:"MX",phoneCode:"52", flag:Flag(countryCode: "MX")),
            Country(name: "country_region_name_md".localizedString(), isoCode:"MD",phoneCode:"373", flag:Flag(countryCode: "MD")),
            // Country(name: "country_region_name_mc".localizedString(), isoCode:"MC",phoneCode:"377", flag:Flag(countryCode: "MC")),
            // Country(name: "country_region_name_mo".localizedString(), isoCode:"MO",phoneCode:"853", flag:Flag(countryCode: "MO")),
            // Country(name: "country_region_name_me".localizedString(), isoCode:"ME",phoneCode:"382", flag:Flag(countryCode: "ME")),
            Country(name: "country_region_name_ms".localizedString(), isoCode:"MS",phoneCode:"1", flag:Flag(countryCode: "MS")),
            Country(name: "country_region_name_ma".localizedString(), isoCode:"MA",phoneCode:"212", flag:Flag(countryCode: "MA")),
            Country(name: "country_region_name_mz".localizedString(), isoCode:"MZ",phoneCode:"258", flag:Flag(countryCode: "MZ")),
            Country(name: "country_region_name_mm".localizedString(), isoCode:"MM",phoneCode:"95", flag:Flag(countryCode: "MM")),
            Country(name: "country_region_name_na".localizedString(), isoCode:"NA",phoneCode:"264", flag:Flag(countryCode: "NA")),
            Country(name: "country_region_name_np".localizedString(), isoCode:"NP",phoneCode:"977", flag:Flag(countryCode: "NP")),
            Country(name: "country_region_name_nl".localizedString(), isoCode:"NL",phoneCode:"31", flag:Flag(countryCode: "NL")),
            // Country(name: "country_region_name_an".localizedString(), isoCode:"AN",phoneCode:"599", flag:Flag(countryCode: "AN")),
            // Country(name: "country_region_name_nc".localizedString(), isoCode:"NC",phoneCode:"687", flag:Flag(countryCode: "NC")),
            Country(name: "country_region_name_nz".localizedString(), isoCode:"NZ",phoneCode:"64", flag:Flag(countryCode: "NZ")),
            Country(name: "country_region_name_ni".localizedString(), isoCode:"NI",phoneCode:"505", flag:Flag(countryCode: "NI")),
            Country(name: "country_region_name_ne".localizedString(), isoCode:"NE",phoneCode:"227", flag:Flag(countryCode: "NE")),
            Country(name: "country_region_name_ng".localizedString(), isoCode:"NG",phoneCode:"234", flag:Flag(countryCode: "NG")),
            Country(name: "country_region_name_no".localizedString(), isoCode:"NO",phoneCode:"47", flag:Flag(countryCode: "NO")),
            Country(name: "country_region_name_om".localizedString(), isoCode:"OM",phoneCode:"968", flag:Flag(countryCode: "OM")),
            Country(name: "country_region_name_pk".localizedString(), isoCode:"PK",phoneCode:"92", flag:Flag(countryCode: "PK")),
            // Country(name: "country_region_name_pw".localizedString(), isoCode:"PW",phoneCode:"680", flag:Flag(countryCode: "PW")),
            // Country(name: "country_region_name_ps".localizedString(), isoCode:"PS",phoneCode:"970", flag:Flag(countryCode: "PS")),
            Country(name: "country_region_name_pa".localizedString(), isoCode:"PA",phoneCode:"507", flag:Flag(countryCode: "PA")),
            Country(name: "country_region_name_pg".localizedString(), isoCode:"PG",phoneCode:"675", flag:Flag(countryCode: "PG")),
            Country(name: "country_region_name_py".localizedString(), isoCode:"PY",phoneCode:"595", flag:Flag(countryCode: "PY")),
            Country(name: "country_region_name_pe".localizedString(), isoCode:"PE",phoneCode:"51", flag:Flag(countryCode: "PE")),
            Country(name: "country_region_name_ph".localizedString(), isoCode:"PH",phoneCode:"63", flag:Flag(countryCode: "PH")),
            Country(name: "country_region_name_pl".localizedString(), isoCode:"PL",phoneCode:"48", flag:Flag(countryCode: "PL")),
            Country(name: "country_region_name_pt".localizedString(), isoCode:"PT",phoneCode:"351", flag:Flag(countryCode: "PT")),
            Country(name: "country_region_name_pr".localizedString(), isoCode:"PR",phoneCode:"1", flag:Flag(countryCode: "PR")),
            Country(name: "country_region_name_qa".localizedString(), isoCode:"QA",phoneCode:"974", flag:Flag(countryCode: "QA")),
            // Country(name: "country_region_name_cg".localizedString(), isoCode:"CG",phoneCode:"242", flag:Flag(countryCode: "CG")),
            // Country(name: "country_region_name_re".localizedString(), isoCode:"RE",phoneCode:"262", flag:Flag(countryCode: "RE")),
            // Country(name: "country_region_name_ro".localizedString(), isoCode:"RO",phoneCode:"40", flag:Flag(countryCode: "RO")),
            Country(name: "country_region_name_ru".localizedString(), isoCode:"RU",phoneCode:"7", flag:Flag(countryCode: "RU")),
            Country(name: "country_region_name_rw".localizedString(), isoCode:"RW",phoneCode:"250", flag:Flag(countryCode: "RW")),
            Country(name: "country_region_name_kn".localizedString(), isoCode:"KN",phoneCode:"1", flag:Flag(countryCode: "KN")),
            Country(name: "country_region_name_lc".localizedString(), isoCode:"LC",phoneCode:"1", flag:Flag(countryCode: "LC")),
            Country(name: "country_region_name_vc".localizedString(), isoCode:"VC",phoneCode:"1", flag:Flag(countryCode: "VC")),
            // Country(name: "country_region_name_ws".localizedString(), isoCode:"WS",phoneCode:"685", flag:Flag(countryCode: "WS")),
            // Country(name: "country_region_name_st".localizedString(), isoCode:"ST",phoneCode:"239", flag:Flag(countryCode: "ST")),
            // Country(name: "country_region_name_sa".localizedString(), isoCode:"SA",phoneCode:"966", flag:Flag(countryCode: "SA")),
            Country(name: "country_region_name_sn".localizedString(), isoCode:"SN",phoneCode:"221", flag:Flag(countryCode: "SN")),
            Country(name: "country_region_name_rs".localizedString(), isoCode:"RS",phoneCode:"381", flag:Flag(countryCode: "RS")),
            // Country(name: "country_region_name_sc".localizedString(), isoCode:"SC",phoneCode:"248", flag:Flag(countryCode: "SC")),
            Country(name: "country_region_name_sd".localizedString(), isoCode:"SD",phoneCode:"249", flag:Flag(countryCode: "SD")),
            // Country(name: "country_region_name_sl".localizedString(), isoCode:"SL",phoneCode:"232", flag:Flag(countryCode: "SL")),
            Country(name: "country_region_name_sg".localizedString(), isoCode:"SG",phoneCode:"65", flag:Flag(countryCode: "SG")),
            Country(name: "country_region_name_sk".localizedString(), isoCode:"SK",phoneCode:"421", flag:Flag(countryCode: "SK")),
            Country(name: "country_region_name_si".localizedString(), isoCode:"SI",phoneCode:"386", flag:Flag(countryCode: "SI")),
            Country(name: "country_region_name_sb".localizedString(), isoCode:"SB",phoneCode:"677", flag:Flag(countryCode: "SB")),
            // Country(name: "country_region_name_so".localizedString(), isoCode:"SO",phoneCode:"252", flag:Flag(countryCode: "SO")),
            Country(name: "country_region_name_za".localizedString(), isoCode:"ZA",phoneCode:"27", flag:Flag(countryCode: "ZA")),
            Country(name: "country_region_name_kr".localizedString(), isoCode:"KR",phoneCode:"82", flag:Flag(countryCode: "KR")),
            // Country(name: "country_region_name_ss".localizedString(), isoCode:"SS",phoneCode:"211", flag:Flag(countryCode: "SS")),
            Country(name: "country_region_name_es".localizedString(), isoCode:"ES",phoneCode:"34", flag:Flag(countryCode: "ES")),
            Country(name: "country_region_name_lk".localizedString(), isoCode:"LK",phoneCode:"94", flag:Flag(countryCode: "LK")),
            // Country(name: "country_region_name_sr".localizedString(), isoCode:"SR",phoneCode:"597", flag:Flag(countryCode: "SR")),
            // Country(name: "country_region_name_sz".localizedString(), isoCode:"SZ",phoneCode:"268", flag:Flag(countryCode: "SZ")),
            Country(name: "country_region_name_se".localizedString(), isoCode:"SE",phoneCode:"46", flag:Flag(countryCode: "SE")),
            Country(name: "country_region_name_ch".localizedString(), isoCode:"CH",phoneCode:"41", flag:Flag(countryCode: "CH")),
            Country(name: "country_region_name_tw".localizedString(), isoCode:"TW",phoneCode:"886", flag:Flag(countryCode: "TW")),
            Country(name: "country_region_name_tj".localizedString(), isoCode:"TJ",phoneCode:"992", flag:Flag(countryCode: "TJ")),
            Country(name: "country_region_name_tz".localizedString(), isoCode:"TZ",phoneCode:"255", flag:Flag(countryCode: "TZ")),
            Country(name: "country_region_name_th".localizedString(), isoCode:"TH",phoneCode:"66", flag:Flag(countryCode: "TH")),
            Country(name: "country_region_name_tg".localizedString(), isoCode:"TG",phoneCode:"228", flag:Flag(countryCode: "TG")),
            // Country(name: "country_region_name_to".localizedString(), isoCode:"TO",phoneCode:"676", flag:Flag(countryCode: "TO")),
            Country(name: "country_region_name_tt".localizedString(), isoCode:"TT",phoneCode:"1", flag:Flag(countryCode: "TT")),
            Country(name: "country_region_name_tn".localizedString(), isoCode:"TN",phoneCode:"216", flag:Flag(countryCode: "TN")),
            Country(name: "country_region_name_tr".localizedString(), isoCode:"TR",phoneCode:"90", flag:Flag(countryCode: "TR")),
            Country(name: "country_region_name_tm".localizedString(), isoCode:"TM",phoneCode:"993", flag:Flag(countryCode: "TM")),
            Country(name: "country_region_name_tc".localizedString(), isoCode:"TC",phoneCode:"1", flag:Flag(countryCode: "TC")),
            Country(name: "country_region_name_ug".localizedString(), isoCode:"UG",phoneCode:"256", flag:Flag(countryCode: "UG")),
            Country(name: "country_region_name_ua".localizedString(), isoCode:"UA",phoneCode:"380", flag:Flag(countryCode: "UA")),
            Country(name: "country_region_name_ae".localizedString(), isoCode:"AE",phoneCode:"971", flag:Flag(countryCode: "AE")),
            Country(name: "country_region_name_gb".localizedString(), isoCode:"GB",phoneCode:"44", flag:Flag(countryCode: "GB")),
            Country(name: "country_region_name_us".localizedString(), isoCode:"US",phoneCode:"1", flag:Flag(countryCode: "US")),
            Country(name: "country_region_name_uy".localizedString(), isoCode:"UY",phoneCode:"598", flag:Flag(countryCode: "UY")),
            Country(name: "country_region_name_uz".localizedString(), isoCode:"UZ",phoneCode:"998", flag:Flag(countryCode: "UZ")),
            // Country(name: "country_region_name_vu".localizedString(), isoCode:"VU",phoneCode:"678", flag:Flag(countryCode: "VU")),
            Country(name: "country_region_name_ve".localizedString(), isoCode:"VE",phoneCode:"58", flag:Flag(countryCode: "VE")),
            Country(name: "country_region_name_vn".localizedString(), isoCode:"VN",phoneCode:"84", flag:Flag(countryCode: "VN")),
            Country(name: "country_region_name_vg".localizedString(), isoCode:"VG",phoneCode:"1", flag:Flag(countryCode: "VG")),
            Country(name: "country_region_name_vi".localizedString(), isoCode:"VI",phoneCode:"1", flag:Flag(countryCode: "VI")),
            Country(name: "country_region_name_ye".localizedString(), isoCode:"YE",phoneCode:"967", flag:Flag(countryCode: "YE")),
            Country(name: "country_region_name_zm".localizedString(), isoCode:"ZM",phoneCode:"260", flag:Flag(countryCode: "ZM")),
            Country(name: "country_region_name_zw".localizedString(), isoCode:"ZW",phoneCode:"263", flag:Flag(countryCode: "ZW")),
        ]
    
}
