//
//  Countries.swift
//  CovidSafe
//
//  Copyright © 2020 All rights reserved.
//
import FlagKit

struct CountriesData {
    
    static let countryArray = ["Australia"]

    static let  countries =
        [
//            Country(name: "Country_AF".localizedString(), isoCode:"AF",phoneCode:"93", flag:Flag(countryCode: "AF")),
            Country(name: "Country_AL".localizedString(), isoCode:"AL",phoneCode:"355", flag:Flag(countryCode: "AL")),
            Country(name: "Country_DZ".localizedString(), isoCode:"DZ",phoneCode:"213", flag:Flag(countryCode: "DZ")),
//            Country(name: "Country_AD".localizedString(), isoCode:"AD",phoneCode:"376", flag:Flag(countryCode: "AD")),
            Country(name: "Country_AO".localizedString(), isoCode:"AO",phoneCode:"244", flag:Flag(countryCode: "AO")),
            Country(name: "Country_AI".localizedString(), isoCode:"AI",phoneCode:"1", flag:Flag(countryCode: "AI")),
            Country(name: "Country_AG".localizedString(), isoCode:"AG",phoneCode:"1", flag:Flag(countryCode: "AG")),
            Country(name: "Country_AR".localizedString(), isoCode:"AR",phoneCode:"54", flag:Flag(countryCode: "AR")),
            Country(name: "Country_AM".localizedString(), isoCode:"AM",phoneCode:"374", flag:Flag(countryCode: "AM")),
            Country(name: "Country_AW".localizedString(), isoCode:"AW",phoneCode:"297", flag:Flag(countryCode: "AW")),
//            Country(name: "Country_AU".localizedString(), isoCode:"AU",phoneCode:"61", flag:Flag(countryCode: "AU")),
            Country(name: "Country_AT".localizedString(), isoCode:"AT",phoneCode:"43", flag:Flag(countryCode: "AT")),
            Country(name: "Country_AZ".localizedString(), isoCode:"AZ",phoneCode:"994", flag:Flag(countryCode: "AZ")),
            Country(name: "Country_BS".localizedString(), isoCode:"BS",phoneCode:"1", flag:Flag(countryCode: "BS")),
            Country(name: "Country_BH".localizedString(), isoCode:"BH",phoneCode:"973", flag:Flag(countryCode: "BH")),
            Country(name: "Country_BD".localizedString(), isoCode:"BD",phoneCode:"880", flag:Flag(countryCode: "BD")),
            Country(name: "Country_BB".localizedString(), isoCode:"BB",phoneCode:"1", flag:Flag(countryCode: "BB")),
            Country(name: "Country_BY".localizedString(), isoCode:"BY",phoneCode:"375", flag:Flag(countryCode: "BY")),
            Country(name: "Country_BE".localizedString(), isoCode:"BE",phoneCode:"32", flag:Flag(countryCode: "BE")),
            Country(name: "Country_BZ".localizedString(), isoCode:"BZ",phoneCode:"501", flag:Flag(countryCode: "BZ")),
            Country(name: "Country_BJ".localizedString(), isoCode:"BJ",phoneCode:"229", flag:Flag(countryCode: "BJ")),
            Country(name: "Country_BM".localizedString(), isoCode:"BM",phoneCode:"1", flag:Flag(countryCode: "BM")),
//            Country(name: "Country_BT".localizedString(), isoCode:"BT",phoneCode:"975", flag:Flag(countryCode: "BT")),
            Country(name: "Country_BO".localizedString(), isoCode:"BO",phoneCode:"591", flag:Flag(countryCode: "BO")),
            Country(name: "Country_BA".localizedString(), isoCode:"BA",phoneCode:"387", flag:Flag(countryCode: "BA")),
            Country(name: "Country_BW".localizedString(), isoCode:"BW",phoneCode:"267", flag:Flag(countryCode: "BW")),
            Country(name: "Country_BR".localizedString(), isoCode:"BR",phoneCode:"55", flag:Flag(countryCode: "BR")),
//            Country(name: "Country_BN".localizedString(), isoCode:"BN",phoneCode:"673", flag:Flag(countryCode: "BN")),
            Country(name: "Country_BG".localizedString(), isoCode:"BG",phoneCode:"359", flag:Flag(countryCode: "BG")),
            Country(name: "Country_BF".localizedString(), isoCode:"BF",phoneCode:"226", flag:Flag(countryCode: "BF")),
//            Country(name: "Country_BI".localizedString(), isoCode:"BI",phoneCode:"257", flag:Flag(countryCode: "BI")),
            Country(name: "Country_KH".localizedString(), isoCode:"KH",phoneCode:"855", flag:Flag(countryCode: "KH")),
            Country(name: "Country_CM".localizedString(), isoCode:"CM",phoneCode:"237", flag:Flag(countryCode: "CM")),
            Country(name: "Country_CA".localizedString(), isoCode:"CA",phoneCode:"1", flag:Flag(countryCode: "CA")),
            Country(name: "Country_CV".localizedString(), isoCode:"CV",phoneCode:"238", flag:Flag(countryCode: "CV")),
            Country(name: "Country_KY".localizedString(), isoCode:"KY",phoneCode:"1", flag:Flag(countryCode: "KY")),
//            Country(name: "Country_CF".localizedString(), isoCode:"CF",phoneCode:"236", flag:Flag(countryCode: "CF")),
//            Country(name: "Country_TD".localizedString(), isoCode:"TD",phoneCode:"235", flag:Flag(countryCode: "TD")),
            Country(name: "Country_CL".localizedString(), isoCode:"CL",phoneCode:"56", flag:Flag(countryCode: "CL")),
            Country(name: "Country_CN".localizedString(), isoCode:"CN",phoneCode:"86", flag:Flag(countryCode: "CN")),
            Country(name: "Country_CO".localizedString(), isoCode:"CO",phoneCode:"57", flag:Flag(countryCode: "CO")),
//            Country(name: "Country_KM".localizedString(), isoCode:"KM",phoneCode:"269", flag:Flag(countryCode: "KM")),
//            Country(name: "Country_CK".localizedString(), isoCode:"CK",phoneCode:"682", flag:Flag(countryCode: "CK")),
            Country(name: "Country_CR".localizedString(), isoCode:"CR",phoneCode:"506", flag:Flag(countryCode: "CR")),
            Country(name: "Country_HR".localizedString(), isoCode:"HR",phoneCode:"385", flag:Flag(countryCode: "HR")),
            Country(name: "Country_CU".localizedString(), isoCode:"CU",phoneCode:"53", flag:Flag(countryCode: "CU")),
            Country(name: "Country_CW".localizedString(), isoCode:"CW",phoneCode:"599", flag:Flag(countryCode: "CW")),
            Country(name: "Country_CY".localizedString(), isoCode:"CY",phoneCode:"357", flag:Flag(countryCode: "CY")),
            Country(name: "Country_CZ".localizedString(), isoCode:"CZ",phoneCode:"420", flag:Flag(countryCode: "CZ")),
//            Country(name: "Country_CD".localizedString(), isoCode:"CD",phoneCode:"243", flag:Flag(countryCode: "CD")),
            Country(name: "Country_DK".localizedString(), isoCode:"DK",phoneCode:"45", flag:Flag(countryCode: "DK")),
//            Country(name: "Country_DJ".localizedString(), isoCode:"DJ",phoneCode:"253", flag:Flag(countryCode: "DJ")),
            Country(name: "Country_DM".localizedString(), isoCode:"DM",phoneCode:"1", flag:Flag(countryCode: "DM")),
            Country(name: "Country_DO".localizedString(), isoCode:"DO",phoneCode:"1", flag:Flag(countryCode: "DO")),
//            Country(name: "Country_TL".localizedString(), isoCode:"TL",phoneCode:"670", flag:Flag(countryCode: "TL")),
            Country(name: "Country_EC".localizedString(), isoCode:"EC",phoneCode:"593", flag:Flag(countryCode: "EC")),
//            Country(name: "Country_EG".localizedString(), isoCode:"EG",phoneCode:"20", flag:Flag(countryCode: "EG")),
            Country(name: "Country_SV".localizedString(), isoCode:"SV",phoneCode:"503", flag:Flag(countryCode: "SV")),
//            Country(name: "Country_GQ".localizedString(), isoCode:"GQ",phoneCode:"240", flag:Flag(countryCode: "GQ")),
            Country(name: "Country_EE".localizedString(), isoCode:"EE",phoneCode:"372", flag:Flag(countryCode: "EE")),
//            Country(name: "Country_ET".localizedString(), isoCode:"ET",phoneCode:"251", flag:Flag(countryCode: "ET")),
//            Country(name: "Country_FO".localizedString(), isoCode:"FO",phoneCode:"298", flag:Flag(countryCode: "FO")),
            Country(name: "Country_FJ".localizedString(), isoCode:"FJ",phoneCode:"679", flag:Flag(countryCode: "FJ")),
            Country(name: "Country_FI".localizedString(), isoCode:"FI",phoneCode:"358", flag:Flag(countryCode: "FI")),
            Country(name: "Country_FR".localizedString(), isoCode:"FR",phoneCode:"33", flag:Flag(countryCode: "FR")),
//            Country(name: "Country_GF".localizedString(), isoCode:"GF",phoneCode:"995", flag:Flag(countryCode: "GF")),
            Country(name: "Country_GA".localizedString(), isoCode:"GA",phoneCode:"241", flag:Flag(countryCode: "GA")),
//            Country(name: "Country_GM".localizedString(), isoCode:"GM",phoneCode:"220", flag:Flag(countryCode: "GM")),
            Country(name: "Country_GE".localizedString(), isoCode:"GE",phoneCode:"995", flag:Flag(countryCode: "GE")),
            Country(name: "Country_DE".localizedString(), isoCode:"DE",phoneCode:"49", flag:Flag(countryCode: "DE")),
            Country(name: "Country_GH".localizedString(), isoCode:"GH",phoneCode:"233", flag:Flag(countryCode: "GH")),
//            Country(name: "Country_GI".localizedString(), isoCode:"GI",phoneCode:"350", flag:Flag(countryCode: "GI")),
            Country(name: "Country_GR".localizedString(), isoCode:"GR",phoneCode:"30", flag:Flag(countryCode: "GR")),
//            Country(name: "Country_GL".localizedString(), isoCode:"GL",phoneCode:"299", flag:Flag(countryCode: "GL")),
            Country(name: "Country_GD".localizedString(), isoCode:"GD",phoneCode:"1", flag:Flag(countryCode: "GD")),
//            Country(name: "Country_GP".localizedString(), isoCode:"GP",phoneCode:"224", flag:Flag(countryCode: "GP")),
            Country(name: "Country_GU".localizedString(), isoCode:"GU",phoneCode:"1", flag:Flag(countryCode: "GU")),
            Country(name: "Country_GT".localizedString(), isoCode:"GT",phoneCode:"502", flag:Flag(countryCode: "GT")),
//            Country(name: "Country_GN".localizedString(), isoCode:"GN",phoneCode:"224", flag:Flag(countryCode: "GN")),
            Country(name: "Country_GW".localizedString(), isoCode:"GW",phoneCode:"245", flag:Flag(countryCode: "GW")),
//            Country(name: "Country_GY".localizedString(), isoCode:"GY",phoneCode:"592", flag:Flag(countryCode: "GY")),
            Country(name: "Country_HT".localizedString(), isoCode:"HT",phoneCode:"509", flag:Flag(countryCode: "HT")),
            Country(name: "Country_HN".localizedString(), isoCode:"HN",phoneCode:"504", flag:Flag(countryCode: "HN")),
            Country(name: "Country_HK".localizedString(), isoCode:"HK",phoneCode:"852", flag:Flag(countryCode: "HK")),
            Country(name: "Country_HU".localizedString(), isoCode:"HU",phoneCode:"36", flag:Flag(countryCode: "HU")),
            Country(name: "Country_IS".localizedString(), isoCode:"IS",phoneCode:"354", flag:Flag(countryCode: "IS")),
            Country(name: "Country_IN".localizedString(), isoCode:"IN",phoneCode:"91", flag:Flag(countryCode: "IN")),
            Country(name: "Country_ID".localizedString(), isoCode:"ID",phoneCode:"62", flag:Flag(countryCode: "ID")),
            Country(name: "Country_IQ".localizedString(), isoCode:"IQ",phoneCode:"964", flag:Flag(countryCode: "IQ")),
            Country(name: "Country_IE".localizedString(), isoCode:"IE",phoneCode:"353", flag:Flag(countryCode: "IE")),
            Country(name: "Country_IL".localizedString(), isoCode:"IL",phoneCode:"972", flag:Flag(countryCode: "IL")),
            Country(name: "Country_IR".localizedString(), isoCode:"IR",phoneCode:"98", flag:Flag(countryCode: "IR")),
//            Country(name: "Country_IT".localizedString(), isoCode:"IT",phoneCode:"39", flag:Flag(countryCode: "IT")),
            Country(name: "Country_CI".localizedString(), isoCode:"CI",phoneCode:"225", flag:Flag(countryCode: "CI")),
            Country(name: "Country_JM".localizedString(), isoCode:"JM",phoneCode:"1", flag:Flag(countryCode: "JM")),
            Country(name: "Country_JP".localizedString(), isoCode:"JP",phoneCode:"81", flag:Flag(countryCode: "JP")),
            Country(name: "Country_JO".localizedString(), isoCode:"JO",phoneCode:"962", flag:Flag(countryCode: "JO")),
            Country(name: "Country_KZ".localizedString(), isoCode:"KZ",phoneCode:"7", flag:Flag(countryCode: "KZ")),
            Country(name: "Country_KE".localizedString(), isoCode:"KE",phoneCode:"254", flag:Flag(countryCode: "KE")),
//            Country(name: "Country_KI".localizedString(), isoCode:"KI",phoneCode:"686", flag:Flag(countryCode: "KI")),
            Country(name: "Country_KW".localizedString(), isoCode:"KW",phoneCode:"965", flag:Flag(countryCode: "KW")),
            Country(name: "Country_KG".localizedString(), isoCode:"KG",phoneCode:"996", flag:Flag(countryCode: "KG")),
            Country(name: "Country_LA".localizedString(), isoCode:"LA",phoneCode:"856", flag:Flag(countryCode: "LA")),
            Country(name: "Country_LV".localizedString(), isoCode:"LV",phoneCode:"371", flag:Flag(countryCode: "LV")),
            Country(name: "Country_LB".localizedString(), isoCode:"LB",phoneCode:"961", flag:Flag(countryCode: "LB")),
//            Country(name: "Country_LS".localizedString(), isoCode:"LS",phoneCode:"266", flag:Flag(countryCode: "LS")),
//            Country(name: "Country_LR".localizedString(), isoCode:"LR",phoneCode:"231", flag:Flag(countryCode: "LR")),
//            Country(name: "Country_LY".localizedString(), isoCode:"LY",phoneCode:"218", flag:Flag(countryCode: "LY")),
            Country(name: "Country_LI".localizedString(), isoCode:"LI",phoneCode:"423", flag:Flag(countryCode: "LI")),
            Country(name: "Country_LT".localizedString(), isoCode:"LT",phoneCode:"370", flag:Flag(countryCode: "LT")),
            Country(name: "Country_LU".localizedString(), isoCode:"LU",phoneCode:"352", flag:Flag(countryCode: "LU")),
            Country(name: "Country_MO".localizedString(), isoCode:"MO",phoneCode:"853", flag:Flag(countryCode: "MO")),
            Country(name: "Country_MK".localizedString(), isoCode:"MK",phoneCode:"389", flag:Flag(countryCode: "MK")),
//            Country(name: "Country_MG".localizedString(), isoCode:"MG",phoneCode:"261", flag:Flag(countryCode: "MG")),
//            Country(name: "Country_MW".localizedString(), isoCode:"MW",phoneCode:"265", flag:Flag(countryCode: "MW")),
            Country(name: "Country_MY".localizedString(), isoCode:"MY",phoneCode:"60", flag:Flag(countryCode: "MY")),
//            Country(name: "Country_MV".localizedString(), isoCode:"MV",phoneCode:"960", flag:Flag(countryCode: "MV")),
            Country(name: "Country_ML".localizedString(), isoCode:"ML",phoneCode:"223", flag:Flag(countryCode: "ML")),
            Country(name: "Country_MT".localizedString(), isoCode:"MT",phoneCode:"356", flag:Flag(countryCode: "MT")),
            Country(name: "Country_MQ".localizedString(), isoCode:"MQ",phoneCode:"1", flag:Flag(countryCode: "MQ")),
//            Country(name: "Country_MR".localizedString(), isoCode:"MR",phoneCode:"222", flag:Flag(countryCode: "MR")),
            Country(name: "Country_MU".localizedString(), isoCode:"MU",phoneCode:"230", flag:Flag(countryCode: "MU")),
            Country(name: "Country_MX".localizedString(), isoCode:"MX",phoneCode:"52", flag:Flag(countryCode: "MX")),
            Country(name: "Country_MD".localizedString(), isoCode:"MD",phoneCode:"373", flag:Flag(countryCode: "MD")),
//            Country(name: "Country_MC".localizedString(), isoCode:"MC",phoneCode:"377", flag:Flag(countryCode: "MC")),
//            Country(name: "Country_MO".localizedString(), isoCode:"MO",phoneCode:"853", flag:Flag(countryCode: "MO")),
//            Country(name: "Country_ME".localizedString(), isoCode:"ME",phoneCode:"382", flag:Flag(countryCode: "ME")),
            Country(name: "Country_MS".localizedString(), isoCode:"MS",phoneCode:"1", flag:Flag(countryCode: "MS")),
            Country(name: "Country_MA".localizedString(), isoCode:"MA",phoneCode:"212", flag:Flag(countryCode: "MA")),
            Country(name: "Country_MZ".localizedString(), isoCode:"MZ",phoneCode:"258", flag:Flag(countryCode: "MZ")),
            Country(name: "Country_MM".localizedString(), isoCode:"MM",phoneCode:"95", flag:Flag(countryCode: "MM")),
            Country(name: "Country_NA".localizedString(), isoCode:"NA",phoneCode:"264", flag:Flag(countryCode: "NA")),
            Country(name: "Country_NP".localizedString(), isoCode:"NP",phoneCode:"977", flag:Flag(countryCode: "NP")),
            Country(name: "Country_NL".localizedString(), isoCode:"NL",phoneCode:"31", flag:Flag(countryCode: "NL")),
//            Country(name: "Country_AN".localizedString(), isoCode:"AN",phoneCode:"599", flag:Flag(countryCode: "AN")),
//            Country(name: "Country_NC".localizedString(), isoCode:"NC",phoneCode:"687", flag:Flag(countryCode: "NC")),
            Country(name: "Country_NZ".localizedString(), isoCode:"NZ",phoneCode:"64", flag:Flag(countryCode: "NZ")),
            Country(name: "Country_NI".localizedString(), isoCode:"NI",phoneCode:"505", flag:Flag(countryCode: "NI")),
            Country(name: "Country_NE".localizedString(), isoCode:"NE",phoneCode:"227", flag:Flag(countryCode: "NE")),
            Country(name: "Country_NG".localizedString(), isoCode:"NG",phoneCode:"234", flag:Flag(countryCode: "NG")),
            Country(name: "Country_NO".localizedString(), isoCode:"NO",phoneCode:"47", flag:Flag(countryCode: "NO")),
            Country(name: "Country_OM".localizedString(), isoCode:"OM",phoneCode:"968", flag:Flag(countryCode: "OM")),
            Country(name: "Country_PK".localizedString(), isoCode:"PK",phoneCode:"92", flag:Flag(countryCode: "PK")),
//            Country(name: "Country_PW".localizedString(), isoCode:"PW",phoneCode:"680", flag:Flag(countryCode: "PW")),
//            Country(name: "Country_PS".localizedString(), isoCode:"PS",phoneCode:"970", flag:Flag(countryCode: "PS")),
            Country(name: "Country_PA".localizedString(), isoCode:"PA",phoneCode:"507", flag:Flag(countryCode: "PA")),
            Country(name: "Country_PG".localizedString(), isoCode:"PG",phoneCode:"675", flag:Flag(countryCode: "PG")),
            Country(name: "Country_PY".localizedString(), isoCode:"PY",phoneCode:"595", flag:Flag(countryCode: "PY")),
            Country(name: "Country_PE".localizedString(), isoCode:"PE",phoneCode:"51", flag:Flag(countryCode: "PE")),
            Country(name: "Country_PH".localizedString(), isoCode:"PH",phoneCode:"63", flag:Flag(countryCode: "PH")),
            Country(name: "Country_PL".localizedString(), isoCode:"PL",phoneCode:"48", flag:Flag(countryCode: "PL")),
            Country(name: "Country_PT".localizedString(), isoCode:"PT",phoneCode:"351", flag:Flag(countryCode: "PT")),
            Country(name: "Country_PR".localizedString(), isoCode:"PR",phoneCode:"1", flag:Flag(countryCode: "PR")),
            Country(name: "Country_QA".localizedString(), isoCode:"QA",phoneCode:"974", flag:Flag(countryCode: "QA")),
//            Country(name: "Country_CG".localizedString(), isoCode:"CG",phoneCode:"242", flag:Flag(countryCode: "CG")),
//            Country(name: "Country_RE".localizedString(), isoCode:"RE",phoneCode:"262", flag:Flag(countryCode: "RE")),
//            Country(name: "Country_RO".localizedString(), isoCode:"RO",phoneCode:"40", flag:Flag(countryCode: "RO")),
            Country(name: "Country_RU".localizedString(), isoCode:"RU",phoneCode:"7", flag:Flag(countryCode: "RU")),
            Country(name: "Country_RW".localizedString(), isoCode:"RW",phoneCode:"250", flag:Flag(countryCode: "RW")),
            Country(name: "Country_KN".localizedString(), isoCode:"KN",phoneCode:"1", flag:Flag(countryCode: "KN")),
            Country(name: "Country_LC".localizedString(), isoCode:"LC",phoneCode:"1", flag:Flag(countryCode: "LC")),
            Country(name: "Country_VC".localizedString(), isoCode:"VC",phoneCode:"1", flag:Flag(countryCode: "VC")),
//            Country(name: "Country_WS".localizedString(), isoCode:"WS",phoneCode:"685", flag:Flag(countryCode: "WS")),
//            Country(name: "Country_ST".localizedString(), isoCode:"ST",phoneCode:"239", flag:Flag(countryCode: "ST")),
//            Country(name: "Country_SA".localizedString(), isoCode:"SA",phoneCode:"966", flag:Flag(countryCode: "SA")),
            Country(name: "Country_SN".localizedString(), isoCode:"SN",phoneCode:"221", flag:Flag(countryCode: "SN")),
            Country(name: "Country_RS".localizedString(), isoCode:"RS",phoneCode:"381", flag:Flag(countryCode: "RS")),
//            Country(name: "Country_SC".localizedString(), isoCode:"SC",phoneCode:"248", flag:Flag(countryCode: "SC")),
            Country(name: "Country_SD".localizedString(), isoCode:"SD",phoneCode:"249", flag:Flag(countryCode: "SD")),
//            Country(name: "Country_SL".localizedString(), isoCode:"SL",phoneCode:"232", flag:Flag(countryCode: "SL")),
            Country(name: "Country_SG".localizedString(), isoCode:"SG",phoneCode:"65", flag:Flag(countryCode: "SG")),
            Country(name: "Country_SK".localizedString(), isoCode:"SK",phoneCode:"421", flag:Flag(countryCode: "SK")),
            Country(name: "Country_SI".localizedString(), isoCode:"SI",phoneCode:"386", flag:Flag(countryCode: "SI")),
            Country(name: "Country_SB".localizedString(), isoCode:"SB",phoneCode:"677", flag:Flag(countryCode: "SB")),
//            Country(name: "Country_SO".localizedString(), isoCode:"SO",phoneCode:"252", flag:Flag(countryCode: "SO")),
            Country(name: "Country_ZA".localizedString(), isoCode:"ZA",phoneCode:"27", flag:Flag(countryCode: "ZA")),
            Country(name: "Country_KR".localizedString(), isoCode:"KR",phoneCode:"82", flag:Flag(countryCode: "KR")),
//            Country(name: "Country_SS".localizedString(), isoCode:"SS",phoneCode:"211", flag:Flag(countryCode: "SS")),
            Country(name: "Country_ES".localizedString(), isoCode:"ES",phoneCode:"34", flag:Flag(countryCode: "ES")),
            Country(name: "Country_LK".localizedString(), isoCode:"LK",phoneCode:"94", flag:Flag(countryCode: "LK")),
//            Country(name: "Country_SR".localizedString(), isoCode:"SR",phoneCode:"597", flag:Flag(countryCode: "SR")),
//            Country(name: "Country_SZ".localizedString(), isoCode:"SZ",phoneCode:"268", flag:Flag(countryCode: "SZ")),
            Country(name: "Country_SE".localizedString(), isoCode:"SE",phoneCode:"46", flag:Flag(countryCode: "SE")),
            Country(name: "Country_CH".localizedString(), isoCode:"CH",phoneCode:"41", flag:Flag(countryCode: "CH")),
            Country(name: "Country_TW".localizedString(), isoCode:"TW",phoneCode:"886", flag:Flag(countryCode: "TW")),
            Country(name: "Country_TJ".localizedString(), isoCode:"TJ",phoneCode:"992", flag:Flag(countryCode: "TJ")),
            Country(name: "Country_TZ".localizedString(), isoCode:"TZ",phoneCode:"255", flag:Flag(countryCode: "TZ")),
            Country(name: "Country_TH".localizedString(), isoCode:"TH",phoneCode:"66", flag:Flag(countryCode: "TH")),
            Country(name: "Country_TG".localizedString(), isoCode:"TG",phoneCode:"228", flag:Flag(countryCode: "TG")),
//            Country(name: "Country_TO".localizedString(), isoCode:"TO",phoneCode:"676", flag:Flag(countryCode: "TO")),
            Country(name: "Country_TT".localizedString(), isoCode:"TT",phoneCode:"1", flag:Flag(countryCode: "TT")),
            Country(name: "Country_TN".localizedString(), isoCode:"TN",phoneCode:"216", flag:Flag(countryCode: "TN")),
            Country(name: "Country_TR".localizedString(), isoCode:"TR",phoneCode:"90", flag:Flag(countryCode: "TR")),
            Country(name: "Country_TM".localizedString(), isoCode:"TM",phoneCode:"993", flag:Flag(countryCode: "TM")),
            Country(name: "Country_TC".localizedString(), isoCode:"TC",phoneCode:"1", flag:Flag(countryCode: "TC")),
            Country(name: "Country_UG".localizedString(), isoCode:"UG",phoneCode:"256", flag:Flag(countryCode: "UG")),
            Country(name: "Country_UA".localizedString(), isoCode:"UA",phoneCode:"380", flag:Flag(countryCode: "UA")),
            Country(name: "Country_AE".localizedString(), isoCode:"AE",phoneCode:"971", flag:Flag(countryCode: "AE")),
            Country(name: "Country_GB".localizedString(), isoCode:"GB",phoneCode:"44", flag:Flag(countryCode: "GB")),
            Country(name: "Country_US".localizedString(), isoCode:"US",phoneCode:"1", flag:Flag(countryCode: "US")),
            Country(name: "Country_UY".localizedString(), isoCode:"UY",phoneCode:"598", flag:Flag(countryCode: "UY")),
            Country(name: "Country_UZ".localizedString(), isoCode:"UZ",phoneCode:"998", flag:Flag(countryCode: "UZ")),
//            Country(name: "Country_VU".localizedString(), isoCode:"VU",phoneCode:"678", flag:Flag(countryCode: "VU")),
            Country(name: "Country_VE".localizedString(), isoCode:"VE",phoneCode:"58", flag:Flag(countryCode: "VE")),
            Country(name: "Country_VN".localizedString(), isoCode:"VN",phoneCode:"84", flag:Flag(countryCode: "VN")),
            Country(name: "Country_VG".localizedString(), isoCode:"VG",phoneCode:"1", flag:Flag(countryCode: "VG")),
            Country(name: "Country_VI".localizedString(), isoCode:"VI",phoneCode:"1", flag:Flag(countryCode: "VI")),
            Country(name: "Country_YE".localizedString(), isoCode:"YE",phoneCode:"967", flag:Flag(countryCode: "YE")),
            Country(name: "Country_ZM".localizedString(), isoCode:"ZM",phoneCode:"260", flag:Flag(countryCode: "ZM")),
            Country(name: "Country_ZW".localizedString(), isoCode:"ZW",phoneCode:"263", flag:Flag(countryCode: "ZW")),
        ]
    
}
